Totalsegmentator dataset
neuro-ml/amid pull request #9
Opened 2022-12-23 06:51 UTC by shevtsovalexey

2022-12-23 09:12 UTC, maxme1 requested changes

2022-12-23 09:12 UTC, maxme1 commented on amid/totalsegmentator/anatomical_structures.json
> +["vertebrae_T1", "hip_right", "lung_upper_lobe_left", "rib_right_8", "rib_left_7", "esophagus", "pulmonary_artery", "stomach", "rib_left_11", "gallbladder", "vertebrae_C1", "rib_right_4", "vertebrae_
better create a `.py` file for that, and import the constant from it

2022-12-23 09:12 UTC, maxme1 commented on amid/totalsegmentator/dataset.py
> +            scope[anatomical_structure] = make_loader(anatomical_structure)
move this function outside, or make it a staticmethod

2022-12-23 15:00 UTC, maxme1 requested changes

2022-12-23 15:00 UTC, maxme1 commented on amid/totalsegmentator/dataset.py
> +            yield unpacked, False
why not just import from bimcv?

2022-12-23 15:00 UTC, maxme1 commented on amid/totalsegmentator/dataset.py
> +            return pd.read_csv(zf.open(file), sep=';').head()
also use unpack

2022-12-23 15:00 UTC, maxme1 commented on amid/totalsegmentator/dataset.py
> +            namelist = [x.rstrip('/') for x in zf.namelist()]
use unpack

2022-12-23 15:02 UTC, shevtsovalexey commented on amid/totalsegmentator/dataset.py
> +            yield unpacked, False
works with `.tar.gz` only

2022-12-24 18:53 UTC, maxme1 approved these changes

2022-12-24 19:24 UTC, merged